/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdmissionsCtaV3: typeof import('./src/components/home/v3/AdmissionsCtaV3.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BentoGridSection: typeof import('./src/components/home/v2/BentoGridSection.vue')['default']
    BigCtaSection: typeof import('./src/components/home/v2/BigCtaSection.vue')['default']
    CertificationSection: typeof import('./src/components/home/CertificationSection.vue')['default']
    CourseCard: typeof import('./src/components/ui/CourseCard.vue')['default']
    CtaBanner: typeof import('./src/components/home/CtaBanner.vue')['default']
    CtaSection: typeof import('./src/components/home/v5/CtaSection.vue')['default']
    CtaSectionV4: typeof import('./src/components/home/v4/CtaSectionV4.vue')['default']
    FaqAccordion: typeof import('./src/components/ui/FaqAccordion.vue')['default']
    FaqSection: typeof import('./src/components/home/FaqSection.vue')['default']
    FeatureCard: typeof import('./src/components/ui/FeatureCard.vue')['default']
    FeaturesSection: typeof import('./src/components/home/FeaturesSection.vue')['default']
    FooterV4: typeof import('./src/components/home/v4/FooterV4.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    HeroSectionV2: typeof import('./src/components/home/v2/HeroSectionV2.vue')['default']
    HeroSectionV3: typeof import('./src/components/home/v3/HeroSectionV3.vue')['default']
    HeroSectionV4: typeof import('./src/components/home/v4/HeroSectionV4.vue')['default']
    HomeV5: typeof import('./src/components/home/v5/HomeV5.vue')['default']
    LogosStripV4: typeof import('./src/components/home/v4/LogosStripV4.vue')['default']
    MinimalStatsSection: typeof import('./src/components/home/v2/MinimalStatsSection.vue')['default']
    ModernTestimonials: typeof import('./src/components/home/v2/ModernTestimonials.vue')['default']
    NavbarV4: typeof import('./src/components/home/v4/NavbarV4.vue')['default']
    OutcomesSection: typeof import('./src/components/home/v5/OutcomesSection.vue')['default']
    PathwayCard: typeof import('./src/components/ui/PathwayCard.vue')['default']
    PathwaysSection: typeof import('./src/components/home/PathwaysSection.vue')['default']
    PopularCoursesV3: typeof import('./src/components/home/v3/PopularCoursesV3.vue')['default']
    ProgramCard: typeof import('./src/components/ui/ProgramCard.vue')['default']
    ProgramGridV4: typeof import('./src/components/home/v4/ProgramGridV4.vue')['default']
    ProgramsSection: typeof import('./src/components/home/ProgramsSection.vue')['default']
    QuizComponent: typeof import('./src/components/app/QuizComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionBadge: typeof import('./src/components/ui/SectionBadge.vue')['default']
    SectionHeading: typeof import('./src/components/ui/SectionHeading.vue')['default']
    StarRating: typeof import('./src/components/ui/StarRating.vue')['default']
    StatsSectionV3: typeof import('./src/components/home/v3/StatsSectionV3.vue')['default']
    TestimonialCard: typeof import('./src/components/ui/TestimonialCard.vue')['default']
    TestimonialSliderV4: typeof import('./src/components/home/v4/TestimonialSliderV4.vue')['default']
    TestimonialsSection: typeof import('./src/components/home/TestimonialsSection.vue')['default']
    TheFooter: typeof import('./src/components/layout/TheFooter.vue')['default']
    TheNavbar: typeof import('./src/components/layout/TheNavbar.vue')['default']
    ValuePropV4: typeof import('./src/components/home/v4/ValuePropV4.vue')['default']
    ValuesSection: typeof import('./src/components/home/v5/ValuesSection.vue')['default']
    WhyChooseUsV3: typeof import('./src/components/home/v3/WhyChooseUsV3.vue')['default']
  }
}
